basePath: 这里写base path`
host: 这里写接口服务的host`
info:
  contact:
    email: support@swagger.io`
    name: 这里写联系人信息`
    url: '[http://www.swagger.io/support](http://www.swagger.io/support)`'
  description: 这里写描述信息`
  license:
    name: Apache 2.0`
    url: '[http://www.apache.org/licenses/LICENSE-2.0.html](http://www.apache.org/licenses/LICENSE-2.0.html)`'
  termsOfService: '[http://swagger.io/terms/](http://swagger.io/terms/)`'
  title: 这里写标题`
  version: 1.0`
paths:
  /api/v1/TestPost:
    post:
      consumes:
      - application/json
      description: 测试post接口
      parameters:
      - description: Sheldon's salary is 80w
        in: path
        name: name
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: ""
        "500":
          description: ""
      summary: TestPost
  /api/v1/TestPostStruct:
    post:
      consumes:
      - application/json
      description: 测试post接口
      parameters:
      - description: Sheldon's salary is 80w
        in: path
        name: name
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: ""
        "500":
          description: ""
      summary: TestPostStruct
  /api/v1/ping:
    post:
      consumes:
      - application/json
      description: 状态检查接口
      parameters:
      - description: 验证参数Bearer和token空格拼接
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: ""
        "500":
          description: ""
      summary: Ping
  /api/v1/testlog:
    get:
      consumes:
      - application/json
      description: 测试日志接口
      parameters:
      - description: Sheldon's salary is 80w
        in: path
        name: name
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: ""
        "500":
          description: ""
      summary: TestLog
swagger: "2.0"
